### ISSUE TITLE
Подборка картинок для 2-ой части игры

### ISSUE THREAD

**Issue by spokoynbIy9** [spokoynbIy9/project-2023#4]

**Comment by pretzelVillain** [comment]
![1](https://user-images.githubusercontent.com/131616112/234054647-7c0492c7-e4ab-4adf-b096-ca28789e8d9d.jpg)
![2](https://user-images.githubusercontent.com/131616112/234054654-2107e091-9846-43c2-9605-e5fe33d3a402.jpg)
![3](https://user-images.githubusercontent.com/131616112/234054655-13355a0f-8f96-4ff5-8daf-b5d51ec48674.jpg)
