### ISSUE TITLE
Подборка картинок для 3-й части игры

### ISSUE THREAD

**Issue by spokoynbIy9** [spokoynbIy9/project-2023#5]

**Comment by pretzelVillain** [comment]
![1](https://user-images.githubusercontent.com/131616112/234055179-3671c2ff-71d0-4eec-acd5-4412a57171c0.jpg)
![2](https://user-images.githubusercontent.com/131616112/234055187-fb2b30c7-3777-4774-a610-5a2b53582f5d.jpg)
![3](https://user-images.githubusercontent.com/131616112/234055189-2e1e37cb-4fd4-47fd-99cd-9912b2fba3fc.jpg)
![4](https://user-images.githubusercontent.com/131616112/234055190-159a2084-71b7-4b86-ab15-7a051faddf13.jpg)
![5](https://user-images.githubusercontent.com/131616112/234055191-8e27a637-e15a-4715-8764-2ef273114b4a.jpg)
![6](https://user-images.githubusercontent.com/131616112/234055195-8dbc8e33-48ae-454a-9c27-5870f7cd7ba1.jpg)
![7](https://user-images.githubusercontent.com/131616112/234055197-d61c264f-e9b5-43dd-ae84-345820cf6d65.jpg)
![8](https://user-images.githubusercontent.com/131616112/234055198-56e41e47-8aeb-48eb-b42c-f2f33cfc0a46.jpg)
![9](https://user-images.githubusercontent.com/131616112/234055204-dcd3a0f5-7a81-425d-b99c-37ae42be0b12.jpg)
![10](https://user-images.githubusercontent.com/131616112/234055207-2cc1c6d8-9958-44ef-8ca1-a2ffce2d6ab8.jpg)
